# general data
title: lautisilber
email: lautisilbergleit@gmail.com
description: lautisilber's landing page
github_username: lautisilber

# build settings
exclude: ['README.md']
markdown: kramdown
theme: jekyll-theme-cayman
github:
  zip_url: https://github.com/lautisilber/Labino_esp32_public/archive/1.2.zip
  tar_url: https://github.com/lautisilber/Labino_esp32_public/archive/1.2.tar.gz

# setting I added myself!
repo_links:
  labino_esp32_public:
    name: Labino ESP32
    url: /Labino_esp32_public
