# general data
title: lautisilber
email: lautisilbergleit@gmail.com
description: lautisilber's landing page
github_username: lautisilber

# build settings
exclude: ['README.md']
markdown: kramdown
theme: jekyll-theme-cayman

# setting I added myself!
repo_links:
  labino_esp32_public:
    name: Labino ESP32
    url: /Labino_esp32_public